### ISSUE TITLE
What Atom package did you use for the conflict resolution UI?

### ISSUE THREAD

**Issue by glennon** [githubteacher/merge-conflicts#3]
I think you already had it installed and I missed its name. I haven't used Atom packages/plugins before, so excuse the naive question.

**Comment by Kevin-C-Bell** [comment]
Merge conflicts detect

**Comment by patrickmckenna** [comment]
@glennon @Kevin-C-Bell It's actually called [merge conflicts](https://atom.io/packages/merge-conflicts). Sorry for not writing that down earlier!
