### ISSUE TITLE
Feedback from new git user

### ISSUE THREAD

**Issue by Khillasaurus** [githubteacher/merge-conflicts#7]
*The class was great!*
===
### What I knew going in:
- I went in expecting it to be more advanced than what I already know about git, as I am quite new to git.
- I currently use the command line for everything except committing changed and new files. (I use the "github for windows client"). Cloning, branching, merging, pulling, etc I do via the command line.

### How I felt the class went:
- As expected, the class was slightly more advanced than what I already know, but I landed up learning a ton!
- Some of the things I learnt I plan on using immediately, while others I hope to incorporate after reading up on some documentation a bit more.
- Everything discussed seemed very useful and relevant.

### Other remarks:
- The teacher @patrickmckenna discussed both of my questions in spite of the short time duration, to which I thank you.
- If possible, a slightly longer class would be nice (somewhere between 30%-100% longer) in order to keep everyone caught up, as well as go more in depth regarding difficult topics, and to allow for more question and answer time.

**Comment by patrickmckenna** [comment]
Thanks for such detailed feedback @Khillasaurus, really appreciate it! Hope to see you in future classes.

**Comment by Khillasaurus** [comment]
You're welcome! I'll definitely be back in the future to learn more. (Already enrolled in another upcoming class)
