### ISSUE TITLE
feedback: merge conflicts

### ISSUE THREAD

**Issue by glennon** [githubteacher/merge-conflicts#8]
For a future class, you might want to start with a standard merge conflict resolution using Atom *(update: any text editor)*. That way, students can familiarize themselves with the syntax. It was also slightly difficult to scan the conflict difference between blank space and a normal line of code (e.g., since many blank spaces already exist in both files); Lines like `cout << "This code was written by Sarah.\n";` vs `cout << "Chris wrote this.\n";` might work better.

**Comment by dcam2015** [comment]
I second this, it would also help to have a set of commands to run in case there are set-up issues (which would keep others from keeping pace with the rest of the class).

Additionally it would be great to send out a pre-class poll to see which type of conflict may benefit the audience in case they want to see particular patterns of conflicts resolved versus others.

**Comment by patrickmckenna** [comment]
Appreciate this feedback, @glennon and @dcam2015. Can only give quick answers to a few concerns, but here goes:
- We don't start with Atom, since so many attendees have very strong editor preferences and would feel like we're shilling (even though it's FOSS).
- The hardest part of any class is adapting to a heterogeneous audience, and I completely understand the frustration -- sorry for that.

**Comment by alezandro** [comment]
@patrickmckenna

I thought this webinar was very informative and useful. The pace was a little fast - but that is good. Reviewing the recording and keep experimenting with the repo can help clarify what was shown.

I would be interested in a more advanced follow up class. Especially focusing on using the reflog and more info on rebasing to master.

**Comment by patrickmckenna** [comment]
@alezandro Thanks for the feedback. You may be interested in [this blog post](https://github.com/blog/2019-how-to-undo-almost-anything-with-git), which was written by a fellow trainer.
