### ISSUE TITLE
Question: Git strategy

### ISSUE THREAD

**Issue by dcam2015** [githubteacher/merge-conflicts#9]
@patrickmckenna , at the very start of the class I thought I heard you say that a good git strategy was to commit often or was it to branch often?  I think I was still setting up the environment but wanted to make sure I heard you correctly.  I think you also said something about deleting branches once they have been merged back to master.  Is this also correct?  Wouldn't that mean that we couldn't go back to an earlier stage via reset if we delete an old branch?

**Comment by patrickmckenna** [comment]
@dcam2015 All great questions, and the answer to each is yes:
- branch often (any time you want to start a logically distinct part of work)
- commit often (meaning keep each one focused, and try to tell a story)
- delete branches after merging them

Re: the last one, no, you will not be losing any history. A branch is really a human-friendly name for (or pointer to) a `SHA1`; deleting the branch simply removes the pointer. The commit history remains unchanged.
